- lib/rules/no-unused-styles.js
- lib/util/Components.js
Fix crash on eslint2.0
```
/home/nils/Programmering/ahead/mobile_app/node_modules/eslint/lib/eslint.js:765
throw ex;
^
TypeError: Error while loading rule 'react-native/no-unused-styles': Can't add property react, object is not extensible
at Function.componentRule (/home/nils/Programmering/ahead/mobile_app/node_modules/eslint-plugin-react-native/lib/util/Components.js:110:17)
at /home/nils/Programmering/ahead/mobile_app/node_modules/eslint/lib/eslint.js:754:25
at Array.forEach (native)
at EventEmitter.module.exports.api.verify (/home/nils/Programmering/ahead/mobile_app/node_modules/eslint/lib/eslint.js:729:16)
at processText (/home/nils/Programmering/ahead/mobile_app/node_modules/eslint/lib/cli-engine.js:187:27)
at processFile (/home/nils/Programmering/ahead/mobile_app/node_modules/eslint/ …
```
> Pass utils as another parameter instead of adding on to context fixes

- README.md
- docs/rules/no-color-literals.md
- docs/rules/no-inline-styles.md
- index.js
- lib/rules/no-color-literals.js
- lib/rules/no-inline-styles.js
- lib/util/stylesheet.js
- tests/lib/rules/no-color-literals.js
- tests/lib/rules/no-inline-styles.js
I added two new rules suggested in Issue #23 - `no-inline-styles` checks for style objects with literal values inside JSX style attributes, and `no-color-literals` checks for literal values for properties containing the word `color` in them, both in `StyleSheet` objects and JSX style attributes.
I tried to keep the code style similar to the existing rules, but I think there's probably some refactoring/improving that can be done. They're not perfect but they do work, so I figured I'll send them over for review and if you can let me know what you think.
Thanks!
> new rules: no-inline-styles, no-color-literals

- lib/util/stylesheet.js
E.g. `ExperimentalSpreadProperty` nodes.
Fixes #41 again.
> Handle unrecognized eslint nodes in style rules helper

- lib/util/stylesheet.js
This may happen when using spread operators in stylesheets, as in the example below. I haven't looked into it too deeply -- feel free to improve this PR if you want, but I just wanted it to stop crashing so I could lint 😉 
My code that led to this crash:
```js
const style = StyleSheet.create({
...genericStyle,
...strippedBaseStyle,
});
```
> Don't crash when `node` is null

- README.md
- index.js
- tests/index.js
Hey,
this PR adds a new shared config "all", which can be used to extend from with "plugin:react-native/all".
Closes #17
Shamelessly taken and modified from the eslint-plugin-react codebase :)
Cheers!
> Export shared "all" config

- lib/rules/no-unused-styles.js
- lib/util/stylesheet.js
- tests/lib/rules/no-unused-styles.js
only check a refernce to the style exists in the code and not that it is in a style attribute. Fixes #15
> a more forgiving no-unused-styles

- package.json
[Referring to yarn doc](https://yarnpkg.com/en/docs/dependency-types#toc-dependencies):
> ## `dependencies`
> These are your normal dependencies, or rather ones that you need when running your code (e.g. React or ImmutableJS).
And I think `dependencies` in this repo (`eslint` and `babel-eslint`) should be listed in `devDependencies`.
Why [in this commit](https://github.com/Intellicode/eslint-plugin-react-native/commit/c3d99e47a5475b2eb3c331234fc6020a7cf58f9e?diff=split#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) did you move them to `dependencies`?
> `eslint` and `babel-eslint` should be listed in `devDependencies`

- docs/rules/split-platform-components.md
- lib/rules/split-platform-components.js
- tests/lib/rules/split-platform-components.js
The `import` syntax is commonly used in the React/React Native community but the the `split-platform-components` rule does not capture errors when this pattern is used (#130).
This PR does the following:
> Add support for detecting imported components

- package.json
Fixes issue #133 by updating peer dependency.  Also added ^ in devDependencies and peerDependencies so small upgrades to eslint don't create npm dependency errors.
> Fix eslint dependencies to fix npm dependency errors

- lib/util/stylesheet.js
- tests/lib/rules/no-unused-styles.js
https://github.com/Intellicode/eslint-plugin-react-native/pull/141 was not working for me. This PR also includes a test case to make sure the issue is fixed.
____
The linter crashes with an error when the spread operator
was used in a stylesheet object. This fix will ignore all
styles that are not of type Property.
Fix #129
> fix(no-unused-styles): allow use of spread operator

- lib/rules/split-platform-components.js
- tests/lib/rules/split-platform-components.js
This stops the split-platform-components from complaining when you import a platform specific component in a platform specific test file: `.ios.test.js`.
> split-platform-components works on '.test' files also

- package.json
This updates the peer dependencies to accept either eslint version 3 or 4, to remove warning on install.
eslint-plugin-react does this as shown here:
https://github.com/yannickcr/eslint-plugin-react/blob/master/package.json#L38
> Add eslint 4 to peer dependencies

- tests/lib/rules/no-unused-styles.js
otherwise validations schema is leaked to 'split-platform-components'
> Fix tests in master

- tests/lib/rules/no-color-literals.js
- tests/lib/rules/no-inline-styles.js
- tests/lib/rules/no-unused-styles.js
- tests/lib/rules/split-platform-components.js
I recently wrote a small codemod to transform the eslint tests from using the `code: ['','',''].join('\n')` syntax to use the template literal syntax instead.
The code is available at: https://astexplorer.net/#/gist/000b6e8110a245ca6384c260b954e452/1687ee893085fdae7119c809294e5ed43a3fe428
All tests of this project were able to translate quite nicely.  I'm not sure if you want this change but IMHO it makes working with tests much much easier. 😄 
There's 1 comment that I had to re-add, please check if it's in the right location.
> Refactor tests to use template literals instead of .join() syntax

- lib/util/stylesheet.js
- tests/lib/rules/no-inline-styles.js
Issue #185 (https://github.com/Intellicode/eslint-plugin-react-native/issues/185) is that when there is an unary expression with a variable (eg `+blah` or `-foo`) in the style it is flagged for the rule. Only styles with literal values should be flagged (eg `-1` or `+5` ), whereas those with any variables should be allowed (per the description in the rule docs)
> no-inline-styles false triggers on unary variables

- README.md
This will prevent the npm modules from being deployed with a production bundle.
> Adding --save-dev to npm install commands in the README.md

- .gitignore
- README.md
- docs/rules/no-raw-text.md
- index.js
- lib/rules/no-raw-text.js
- tests/lib/rules/no-raw-text.js
- added new rule to prevent error of raw text, eg
https://github.com/facebook/react-native/issues/15870
https://github.com/react-community/react-native-maps/issues/1791
- added .idea folder to gitignore
> Added no-raw-text rule

- lib/rules/no-color-literals.js
- lib/rules/no-unused-styles.js
- lib/util/stylesheet.js
- tests/lib/rules/no-unused-styles.js
Added support for https://github.com/vitalets/react-native-extended-stylesheet
> Added support of other style sheet providers (eg EStyleSheet)

- README.md
- docs/rules/sort-styles.md
- index.js
- lib/rules/sort-styles.js
- package-lock.json
- tests/lib/rules/sort-styles.js
It's like [sort-keys](https://eslint.org/docs/rules/sort-keys), but just for React Native styles.
Keeping your style definitions sorted is a common convention that helps with readability. This rule lets you enforce an ascending (default) or descending alphabetical order for both "class names" and style properties.
In addition to the tests, I have started using this on my team's RN project. So far, everything looks good! There is a weakness though, this rule will not handle the spread operator in styles very well. I'll see if I find the time to improve this sometime.
> Add sort-styles rule

- README.md
The 'ecmaFeatures' config file property is deprecated so we should use "parserOptions" > "ecmaFeatures" instead.
> Use "parserOptions" instead of just "ecmaFeatures"

- lib/rules/sort-styles.js
- lib/util/stylesheet.js
- tests/lib/rules/sort-styles.js
> Try to fix #213 
Now we can lint some simple template string like: (with default configs)
```js
const styles = StyleSheet.create({
'Text--underlined': {},
'Text--basic': {}
})
// `error  Expected class names to be in ascending order.
//    'Text--basic' should be before 'Text--underlined'  react-native/sort-styles`
```
```js
const prefix = 'Text'
const styles = StyleSheet.create({
[`${prefix}Wrapper`]: {},
[`${prefix}Container`]: {}
})
// `error  Expected class names to be in ascending order.
//    'TextContainer' should be before 'TextWrapper'  react-native/sort-styles`
```
---
By the way, other expressions like `BinaryExpression` or `AssignmentExpression` was not implemented yet.
I think it is a little bit abusing `StyleSheet`?
> Allow using StringLiteral as properties of StyleSheet 

- lib/rules/sort-styles.js
- lib/util/stylesheet.js
- tests/lib/rules/sort-styles.js
- added autofix for 'sort-styles' rule.
> autofix for 'sort-styles' rule

- lib/rules/no-color-literals.js
- lib/rules/no-unused-styles.js
- lib/rules/sort-styles.js
- lib/util/stylesheet.js
- tests/lib/rules/sort-styles.js
Fixes #214
Instead of only looking for `StyleSheet` declarations in `VariableDeclarator` nodes, we check if `CallExpressions` are `StyleSheet.create({...})`. This handles the `export default StyleSheet.create({...})` case and other cases where the style sheet is not assigned to a variable.
> Find StyleSheet declarations that are not variables

- .gitignore
- lib/rules/no-raw-text.js
- package.json
- tests/lib/rules/no-raw-text.js
- yarn.lock
- fixed rule for @typescript-eslint/parser
- added @typescript-eslint/parser as devDependency
- added .DS_Store to .gitignore
> Fixed no-raw-text rule for typescript

- .eslintrc
- lib/rules/no-color-literals.js
- lib/rules/no-inline-styles.js
- lib/rules/no-raw-text.js
- lib/rules/no-unused-styles.js
- lib/rules/sort-styles.js
- lib/rules/split-platform-components.js
- lib/util/Components.js
- lib/util/stylesheet.js
- lib/util/variable.js
- package-lock.json
- package.json
- tests/index.js
- tests/lib/rules/no-color-literals.js
- tests/lib/rules/no-inline-styles.js
- tests/lib/rules/no-raw-text.js
- tests/lib/rules/no-single-element-style-arrays.js
- tests/lib/rules/no-unused-styles.js
- tests/lib/rules/sort-styles.js
- tests/lib/rules/split-platform-components.js
Our security team asked us to eliminate packages with security vulnerabilities, this included updating to eslint 6.x.x.
This commit updates to eslint 6.x.x and fixes tests.
> chore: Update eslint and peer dependencies

- lib/rules/no-raw-text.js
- package.json
- tests/lib/rules/no-raw-text.js
- yarn.lock
When building component packages at scale it can be useful to be able to able to use object dot notation to reduce import noise and to increase readability for highly related components.
An example would be for building a opinionated text components form a style build.
Instead of having:
```js
import { Paragraph, ParagraphLarge, ParagraphSmall } from 'your-component-library'
export const Component = ({ children }) => 
<>
<ParagraphLarge>Header</ParagraphLarge>
<Paragraph>Detail</Paragraph>
<ParagraphSmall>{children}</ParagraphSmall>
</>
```
You could have :
```js
import { Paragraph } from 'your-component-library'
export const Component = ({ children }) => 
<>
<Paragraph.Large>Header</Paragraph.Large>
<Paragraph>Detail</Paragraph>
<Paragraph.Small>{children}</Paragraph.Small>
</>
``` …
> feat: adding support for object notation components for no-raw-text exclusion rule

- package.json
This plugin has no issues with eslint 7.x so we should not want when using it.
> fix: don't warn when using eslint v7

- lib/rules/split-platform-components.js
Currently only `.js` files are recognized by the `split-platform-components` rule. This update should allow for TypeScript support as well.
> Support TypeScript in split-platform-components

- lib/rules/sort-styles.js
- tests/lib/rules/sort-styles.js
If the style properties had a 'isEitherShorthand' case, it would return out of the whole checkIsSorted function instead of continuing the for loop. This caused some properties to not be reported as unsorted.
It would be sufficient to replace `return` with `continue`, but there was a ESLint rule disallowing the usage of continue.
I added a new test case for this scenario.
> Fix bug in sort-styles when props included shorthands

- lib/util/Components.js
- tests/lib/rules/no-unused-styles.js
Components with shorthand Fragments (`<></>`) weren't being traversed in no-unused-styles.
Using these styles:
```
const styles = StyleSheet.create({
used: {},
unused: {},
});
```
```
const CorrectlyFails1 = () => {
return (<Text style={styles.used}>Hello</Text>);
}
```
```
const CorrectlyFails1 = () => {
return (<React.Fragment><Text style={styles.used}>Hello</Text></React.Fragment>);
}
```
```
const IncorrectlyPasses = () => {
return (<><Text style={styles.used}>Hello</Text></>);
}
```
> Fix unused style fragment shorthand

- lib/rules/no-single-element-style-arrays.js
This fixes an issue when a React Native component has style prop that can be a string.
The most notable example of this is the default `App.js` (or App.tsx) in a new React Native app (initialized using `expo init`, as recommended by the [RN docs](https://reactnative.dev/docs/environment-setup)). It looks like this:
Notice line 9 which contains: `<StatusBar style="auto" />`
That causes the following exception when running `eslint`:
> fix: rule/no-single-element-style-arrays - exception when style prop is not an expression

- docs/rules/split-platform-components.md
This PR is updating the documentation of `split-platform-components` rule, adding the `Rule Options` for `androidPathRegex` and `iosPathRegex` options. It is based on the discussion we had in #238 . Thank you.
> Added Rule Options documentation for split-platform-components rule

- lib/rules/no-color-literals.js
- lib/rules/no-inline-styles.js
- lib/rules/no-raw-text.js
- lib/rules/no-unused-styles.js
- lib/rules/sort-styles.js
- lib/rules/split-platform-components.js
- package.json
Fixes https://github.com/Intellicode/eslint-plugin-react-native/issues/298. Verified all tests pass.
From [eslint docs](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#rules-require-metafixable-to-provide-fixes):
> In ESLint v7.0.0, rules that were written as a function (rather than object) were able to provide fixes. In ESLint v8.0.0, only rules written as an object are allowed to provide fixes and must have a meta.fixable property set to either "code" or "whitespace".
> Switch rules to object export style (fixes eslint v8+)

- lib/rules/no-raw-text.js
- package-lock.json
- package.json
- tests/lib/rules/no-raw-text.js
Fixes #270. babel-traverse expects that it's passed an entire tree that spans to the top of the program. eslint does not guarantee that, which causes crashes when parsing some programs (see #270 for many examples).
- Don't rely on the external library. Instead, just iterate through the node ourselves to get the full name
- **Side fix:** Add support so that even nested components inside of a `Text` or other allowed components are allowed. Nested text components can safely be used to add inline bold/color/other styling
Added automated test based on repro case from #270: https://github.com/Intellicode/eslint-plugin-react-native/issues/270#issuecomment-897766305
> Remove dependency on @babel/traverse to fix linting issues

- lib/util/Components.js
- lib/util/variable.js
- package-lock.json
- package.json
Hola!
These changes makes implmentation with eslint 9.x.x working without any compat or hassle!
So if anyone wants to merge, we can move this package forward :)
> flat config eslint 9.x.x working
